[package]
name = "tlsnotary"
version.workspace = true
edition.workspace = true

[dependencies]
async-compat.workspace = true
futures.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
pest.workspace = true
pest_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
smol.workspace = true
thiserror.workspace = true
tlsn.workspace = true
tokio.workspace = true
tracing.workspace = true
