[profile.default]
src = "evm/src"
test = "evm/test"
out = "out"
libs = ["dependencies"]
ignored_warnings_from = ["evm/src/generated/HonkVerifier.sol"]
fs_permissions = [{ access = "read", path = "./evm/testdata" }]

[dependencies]
forge-std = "1.15.0"

[lint]
ignore = ["evm/src/generated/HonkVerifier.sol"]
lint_on_build = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
