[profile.default]
src = "evm"
out = "out"
libs = ["dependencies"]
fs_permissions = [{ access = "read", path = "./evm/testdata" }]

[dependencies]
forge-std = "1.15.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
