[package]
name = "zk"
version.workspace = true
edition.workspace = true

[dependencies]
circuits = { git = "https://github.com/piotr-stec/stwo-circuits", branch="feat/poseidon-instead-blake" }
circuit-prover = { git = "https://github.com/piotr-stec/stwo-circuits", branch="feat/poseidon-instead-blake" }
circuit-common = { git = "https://github.com/piotr-stec/stwo-circuits", branch="feat/poseidon-instead-blake" }
circuit-air = { git = "https://github.com/piotr-stec/stwo-circuits", branch="feat/poseidon-instead-blake" }
stwo = { git = "https://github.com/piotr-stec/stwo", branch = "keccak-latest", features = ["parallel"], default-features = false }
poseidon-m31.workspace = true