[package]
name = "e2e"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
alloy-sol-types.workspace = true
anyhow.workspace = true
askama.workspace = true
async-compat.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
hex.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
pem.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
salvo.workspace = true
salvo-http3.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shared.workspace = true
smol.workspace = true
thiserror.workspace = true
tlsn.workspace = true
tlsnotary.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zktlsn.workspace = true
