[package]
name = "stwo-circuit"
version.workspace = true
edition.workspace = true

[dependencies]
alloy.workspace = true
async-compat.workspace = true
itertools.workspace = true
num-traits.workspace = true
serde.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
dotenvy.workspace = true
thiserror.workspace = true
circuit-air.workspace = true
circuits.workspace = true
circuits-stark-verifier.workspace = true
circuit-common.workspace = true
circuit-prover.workspace = true
# stwo
stwo = { git = "https://github.com/starkware-libs/stwo", rev = "aeceb74c", features = [
    "parallel",
], default-features = false }
stwo-constraint-framework = {  git = "https://github.com/starkware-libs/stwo", rev = "aeceb74c", features = [
    "parallel",
] }
stwo-air-utils-derive = { git = "https://github.com/starkware-libs/stwo", rev = "aeceb74c" }
stwo-air-utils = { git = "https://github.com/starkware-libs/stwo", rev = "aeceb74c" }

[dev-dependencies]
axum.workspace = true
futures.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
quinn.workspace = true
serde_json.workspace = true
shared.workspace = true
smol.workspace = true
tlsnotary.workspace = true
tokio = { workspace = true, features = ["io-util", "time"] }
zkhash = { git = "https://github.com/AntoineFONDEUR/poseidon2.git", branch = "poseidon2-M31" }
