[package]
name = "demo"
version.workspace = true
edition.workspace = true

[[bin]]
name = "zktlsn"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
askama.workspace = true
async-compat.workspace = true
chrono.workspace = true
clap.workspace = true
futures.workspace = true
hex.workspace = true
hyper-util.workspace = true
pem.workspace = true
quinn.workspace = true
rcgen.workspace = true
rustls.workspace = true
salvo.workspace = true
salvo-http3.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zktlsn_core.workspace = true
zk = { path = "../zk" }
